#  Copyright 2021 Xiaodong Xu, 763795151@qq.com
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
server:
  port: 9097

spring:
  application:
    name: kafka-exporter
logging:
  home: ./
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
      base-path: /
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      defaults:
        enabled: true
    use-global-registry: false

collect:
  cron:
    topic: "-"
    consumer: 0/3 * * * * ?

kafka:
  boot-server: localhost:9092
  request-timeout-ms: 3000
  # 服务端是否启用acl了，如果不启用，下面的几项都忽略即可
  enable-acl: false
  security-protocol: SASL_PLAINTEXT
  sasl-mechanism: SCRAM-SHA-256
  sasl-jaas-config: org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin";


metrics:
  excludes:
    - jvm.gc.max.data.size
    - jvm.gc.live.data.size
    - jvm.gc.memory.allocated
    - jvm.gc.memory.promoted
    - jvm.buffer.count
    - jvm.buffer.memory.used
    - jvm.buffer.total.capacity
    - jvm.buffer.count
    - jvm.buffer.memory.used
    - jvm.buffer.total.capacity
    - jvm.memory.used
    - jvm.memory.committed
    - jvm.memory.max
    - jvm.memory.used
    - jvm.memory.committed
    - jvm.memory.max
    - jvm.memory.used
    - jvm.memory.committed
    - jvm.memory.max
    - jvm.memory.used
    - jvm.memory.committed
    - jvm.memory.max
    - jvm.memory.used
    - jvm.memory.committed
    - jvm.memory.max
    - jvm.memory.used
    - jvm.memory.committed
    - jvm.memory.max
    - jvm.threads.peak
    - jvm.threads.daemon
    - jvm.threads.live
    - jvm.threads.states
    - jvm.threads.states
    - jvm.threads.states
    - jvm.threads.states
    - jvm.threads.states
    - jvm.threads.states
    - jvm.classes.loaded
    - jvm.classes.unloaded
    - logback.events
    - logback.events
    - logback.events
    - logback.events
    - logback.events
    - process.uptime
    - process.start.time
    - system.cpu.count
    - system.load.average.1m
    - system.cpu.usage
    - process.cpu.usage
    - process.files.open
    - process.files.max
    - tomcat.sessions.active.max
    - tomcat.sessions.active.current
    - tomcat.sessions.created
    - tomcat.sessions.expired
    - tomcat.sessions.rejected
    - tomcat.sessions.alive.max
    - jvm.gc.pause
    - http.server.requests
